app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: tiger
    pool-size: 20

spring:
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
